name: TCK

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run TCK
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v2

      - name: "checkout submodules"
        run: |
          git submodule init
          git submodule update

      - name: "install spycy"
        run: |
          pip install .

      - name: "install test dependencies"
        run: |
          git clone https://github.com/behave/behave
          cd behave
          pip install -r py.requirements/all.txt
          pip install .

      - name: "Run TCK tests"
        run: |
          cd test/tck
          python3 run_tck.py
